// AUTO-GENERATED. Do not edit by hand.
// Generator: scripts/build-glossary-tsx.py
// To regenerate: python3 scripts/build-glossary-tsx.py
//
// Self-contained Framer Code Component with locale dropdown (en/ko/de).
// Embedded TRANSLATIONS dict drives default text per locale; individual Props
// remain for per-instance overrides. Set `locale` in Framer Properties panel
// to switch all text simultaneously.

import { addPropertyControls, ControlType } from "framer"

interface Props {
  locale?: "en" | "ko" | "de"
  backLabel?: string
  backHref?: string
  term?: string
  lead?: string
  category?: string
  definitionLabel?: string
  definitionBody?: string
  bodyHtml?: string
  related1Label?: string
  related1Href?: string
  related2Label?: string
  related2Href?: string
  related3Label?: string
  related3Href?: string
  related4Label?: string
  related4Href?: string
  related5Label?: string
  related5Href?: string
}

const BODY_HTML = `<h2>Definition</h2>
<p><strong>Operational data</strong> is the structured and unstructured enterprise data generated by ongoing business operations. It includes the records, logs, configurations, alarms, tickets, runbooks, workflows, and contextual references that operations teams produce and consume daily.</p>

<h2>What it is not</h2>
<p>Operational data is not the same as PII. PII is identifiable individual fields — names, contact info, financial identifiers. Operational data may contain PII as a subset, but its sensitivity comes primarily from structure, sequence, and aggregate pattern.</p>

<h2>Examples by industry</h2>

<h3>Telecom</h3>
<ul>
  <li>Network topology, device IDs, site IDs, circuit IDs, IP ranges</li>
  <li>Alarm sequences, traffic anomaly patterns</li>
  <li>Incident records with customer-impact and SLA risk</li>
  <li>NOC response history, runbooks, change management records</li>
</ul>

<h3>OT / Industrial</h3>
<ul>
  <li>Asset IDs, PLC/ICS alerts, vulnerability records</li>
  <li>Plant operation context, patch constraints</li>
  <li>Vendor and device references</li>
</ul>

<h3>Healthcare</h3>
<ul>
  <li>Clinical workflow, lab result flow, prescription flow</li>
  <li>Hospital operation records, claim review context</li>
</ul>

<h3>Defense / Public sector</h3>
<ul>
  <li>Mission logs, operation briefs</li>
  <li>Access-controlled context, command workflow</li>
</ul>

<h3>Finance / Insurance</h3>
<ul>
  <li>Risk review, transaction anomaly</li>
  <li>Audit trail, approval workflow, internal control evidence</li>
</ul>

<h2>Why it needs a context-preserving data layer for AI</h2>
<p>Operational data leaks information through structure (the topology itself reveals the network), sequence (the alarm pattern reveals the fault chain), and aggregate (the incident frequency reveals the customer segment). PII filtering does not bound this leakage. The <a href="/resources/glossary/ai-ready-operational-layer">context-preserving data layer for AI</a> applies <a href="/resources/glossary/structure-preserving-encapsulation">structure-preserving encapsulation</a> with <a href="/resources/glossary/differential-privacy">differential-privacy-based protection</a> to bring operational data safely into LLM workflows.</p>

<h2>Reference statement</h2>
<blockquote>Operational data is the data your business runs on. AI cannot reach it through a PII guardrail. The context-preserving data layer for AI was built for this category specifically.</blockquote>`

const TRANSLATIONS: Record<"en" | "ko" | "de", Record<string, string>> = {
  en: {
    backLabel: "← Glossary",
    backHref: "/resources/glossary",
    term: "Operational Data",
    lead: "The data your business actually runs on. Not the same as PII. Not protected the same way.",
    category: "GLOSSARY",
    definitionLabel: "Definition",
    definitionBody: "Operational data is the structured and unstructured enterprise data generated by ongoing business operations. It includes the records, logs, configurations, alarms, tickets, runbooks, workflows, and contextual references that operations teams produce and consume daily.",
    bodyHtml: BODY_HTML,
    related1Label: "",
    related1Href: "",
    related2Label: "",
    related2Href: "",
    related3Label: "",
    related3Href: "",
    related4Label: "",
    related4Href: "",
    related5Label: "",
    related5Href: "",
  },
  ko: {
    backLabel: "← 용어 사전",
    backHref: "/resources/glossary",
    term: "운영 데이터",
    lead: "비즈니스가 실제로 돌아가는 데이터입니다. PII와 같지 않습니다. 동일한 방식으로 보호되지도 않습니다.",
    category: "GLOSSARY",
    definitionLabel: "정의",
    definitionBody: "운영 데이터는 지속적인 비즈니스 운영 과정에서 생성되는 정형·비정형 기업 데이터입니다. 운영 팀이 매일 생산하고 소비하는 레코드, 로그, 설정 파일, 알람, 티켓, 런북, 워크플로우, 그리고 상황별 참조 정보를 포함합니다.",
    bodyHtml: `<h2>운영 데이터가 아닌 것</h2>

<p>운영 데이터는 PII와 같지 않습니다. PII는 이름, 연락처, 금융 식별자처럼 개인을 특정할 수 있는 필드입니다. 운영 데이터는 PII를 부분 집합으로 포함할 수 있지만, 민감성은 주로 구조, 순서, 집계 패턴에서 비롯됩니다.</p>

<h2>산업별 예시</h2>

<h3>통신</h3>

<ul>
<li>네트워크 토폴로지, 장비 ID, 사이트 ID, 회선 ID, IP 범위</li>
<li>알람 시퀀스, 트래픽 이상 패턴</li>
<li>고객 영향 및 SLA 위험이 포함된 인시던트 기록</li>
<li>NOC 대응 이력, 런북, 변경 관리 기록</li>
</ul>

<h3>OT / 산업</h3>

<ul>
<li>자산 ID, PLC/ICS 알림, 취약점 기록</li>
<li>플랜트 운영 컨텍스트, 패치 제약</li>
<li>벤더 및 장비 참조</li>
</ul>

<h3>의료</h3>

<ul>
<li>임상 워크플로우, 검사 결과 흐름, 처방 흐름</li>
<li>병원 운영 기록, 청구 검토 컨텍스트</li>
</ul>

<h3>국방 / 공공</h3>

<ul>
<li>작전 로그, 작전 브리핑</li>
<li>접근 통제 컨텍스트, 지휘 워크플로우</li>
</ul>

<h3>금융 / 보험</h3>

<ul>
<li>리스크 검토, 거래 이상 탐지</li>
<li>감사 추적, 승인 워크플로우, 내부 통제 증빙</li>
</ul>

<h2>데이터 레이어가 필요한 이유</h2>

<p>운영 데이터는 구조(토폴로지 자체가 네트워크를 드러냄), 순서(알람 패턴이 장애 연쇄를 노출함), 집계(인시던트 빈도가 고객 세그먼트를 노출함)를 통해 정보를 유출합니다. PII 필터링으로는 이 유출을 차단할 수 없습니다. <a href="/resources/glossary/ai-ready-operational-layer">데이터 레이어</a>는 <a href="/resources/glossary/structure-preserving-encapsulation">문서 구조 보존 캡슐화</a>와 <a href="/resources/glossary/differential-privacy">차등 프라이버시 기반 보호</a>를 적용하여 운영 데이터를 LLM 워크플로우에 안전하게 연결합니다.</p>

<h2>핵심 문장</h2>

<blockquote>운영 데이터는 비즈니스가 실제로 돌아가는 데이터입니다. AI는 PII 가드레일만으로 여기에 닿을 수 없습니다. 데이터 레이어는 바로 이 범주를 위해 만들어졌습니다.</blockquote>

---`,
    related1Label: "",
    related1Href: "",
    related2Label: "",
    related2Href: "",
    related3Label: "",
    related3Href: "",
    related4Label: "",
    related4Href: "",
    related5Label: "",
    related5Href: "",
  },
  de: {
    backLabel: "← Glossar",
    backHref: "/resources/glossary",
    term: "Operative Daten",
    lead: "Operative Daten sind die Grundlage des laufenden Geschäftsbetriebs. Sie unterscheiden sich grundlegend von personenbezogenen Daten — und erfordern daher andere Schutzmaßnahmen.",
    category: "GLOSSAR",
    definitionLabel: "Definition",
    definitionBody: "Operative Daten umfassen die strukturierten und unstrukturierten Unternehmensdaten, die im laufenden Betrieb entstehen. Dazu gehören Protokolle, Konfigurationen, Alarmmeldungen, Tickets, Runbooks, Workflows und Kontextdokumente, die von Betriebsteams täglich erzeugt und genutzt werden.",
    bodyHtml: `<h2>Abgrenzung zu personenbezogenen Daten</h2>

<p>Operative Daten sind nicht gleichzusetzen mit personenbezogenen Daten (PII). PII bezeichnet identifizierbare Einzelfelder wie Namen, Kontaktdaten oder Finanzidentifikatoren. Operative Daten können PII als Teilmenge enthalten, ihre Schutzbedürftigkeit ergibt sich jedoch primär aus Struktur, Sequenz und aggregierten Mustern.</p>

<h2>Beispiele nach Branche</h2>

<h3>Telekommunikation</h3>

<ul>
<li>Netzwerktopologie, Geräte-IDs, Standort-IDs, Leitungs-IDs, IP-Adressbereiche</li>
<li>Alarmsequenzen, Anomaliemuster im Datenverkehr</li>
<li>Störungsprotokolle mit Kundenauswirkung und SLA-Risiko</li>
<li>NOC-Reaktionshistorie, Runbooks, Change-Management-Unterlagen</li>
</ul>

<h3>OT / Industrie</h3>

<ul>
<li>Asset-IDs, PLC/ICS-Alarme, Schwachstellenprotokolle</li>
<li>Anlagenbetriebskontext, Patch-Einschränkungen</li>
<li>Hersteller- und Geräteverweise</li>
</ul>

<h3>Gesundheitswesen</h3>

<ul>
<li>Klinische Workflows, Laborergebnisfluss, Verschreibungsabläufe</li>
<li>Krankenhausbetriebsprotokolle, Abrechnungsprüfung</li>
</ul>

<h3>Verteidigung / Öffentlicher Sektor</h3>

<ul>
<li>Einsatzprotokolle, Lagebeschreibungen</li>
<li>Zugriffsgeschützter Kontext, Befehlsabläufe</li>
</ul>

<h3>Finanzen / Versicherung</h3>

<ul>
<li>Risikoprüfung, Transaktionsanomalien</li>
<li>Prüfpfad, Genehmigungsworkflow, interne Kontrollnachweise</li>
</ul>

<h2>Warum ein context-preserving data layer for AI erforderlich ist</h2>

<p>Operative Daten geben Informationen durch ihre Struktur preis (die Topologie selbst offenbart das Netzwerk), durch ihre Sequenz (das Alarmmuster legt die Fehlerkette offen) und durch Aggregate (die Störungshäufigkeit lässt Rückschlüsse auf das Kundensegment zu). Eine PII-Filterung kann diesen Informationsabfluss nicht begrenzen. Der context-preserving data layer for AI wendet strukturerhaltende Kapsulierung mit Differential-Privacy-basiertem Schutz an, um operative Daten sicher in LLM-Workflows einzubinden.</p>

<h2>Kernaussage</h2>

<blockquote>Operative Daten sind die Grundlage des Geschäftsbetriebs. KI kann über einen PII-Filter nicht auf sie zugreifen. Der context-preserving data layer for AI wurde speziell für diese Datenkategorie entwickelt.</blockquote>

---`,
    related1Label: "",
    related1Href: "",
    related2Label: "",
    related2Href: "",
    related3Label: "",
    related3Href: "",
    related4Label: "",
    related4Href: "",
    related5Label: "",
    related5Href: "",
  },
}

export default function OperationalData({
  locale = "en",
  backLabel = "",
  backHref = "",
  term = "",
  lead = "",
  category = "",
  definitionLabel = "",
  definitionBody = "",
  bodyHtml = "",
  related1Label = "",
  related1Href = "",
  related2Label = "",
  related2Href = "",
  related3Label = "",
  related3Href = "",
  related4Label = "",
  related4Href = "",
  related5Label = "",
  related5Href = "",
}: Props) {
  const T = TRANSLATIONS[locale] || TRANSLATIONS.en
  const _backLabel = backLabel || T["backLabel"] || TRANSLATIONS.en["backLabel"]
  const _backHref = backHref || T["backHref"] || TRANSLATIONS.en["backHref"]
  const _term = term || T["term"] || TRANSLATIONS.en["term"]
  const _lead = lead || T["lead"] || TRANSLATIONS.en["lead"]
  const _category = category || T["category"] || TRANSLATIONS.en["category"]
  const _definitionLabel = definitionLabel || T["definitionLabel"] || TRANSLATIONS.en["definitionLabel"]
  const _definitionBody = definitionBody || T["definitionBody"] || TRANSLATIONS.en["definitionBody"]
  const _bodyHtml = bodyHtml || T["bodyHtml"] || TRANSLATIONS.en["bodyHtml"]
  const _related1Label = related1Label || T["related1Label"] || TRANSLATIONS.en["related1Label"]
  const _related1Href = related1Href || T["related1Href"] || TRANSLATIONS.en["related1Href"]
  const _related2Label = related2Label || T["related2Label"] || TRANSLATIONS.en["related2Label"]
  const _related2Href = related2Href || T["related2Href"] || TRANSLATIONS.en["related2Href"]
  const _related3Label = related3Label || T["related3Label"] || TRANSLATIONS.en["related3Label"]
  const _related3Href = related3Href || T["related3Href"] || TRANSLATIONS.en["related3Href"]
  const _related4Label = related4Label || T["related4Label"] || TRANSLATIONS.en["related4Label"]
  const _related4Href = related4Href || T["related4Href"] || TRANSLATIONS.en["related4Href"]
  const _related5Label = related5Label || T["related5Label"] || TRANSLATIONS.en["related5Label"]
  const _related5Href = related5Href || T["related5Href"] || TRANSLATIONS.en["related5Href"]

  const relatedItems = [
    { label: _related1Label, href: _related1Href },
    { label: _related2Label, href: _related2Href },
    { label: _related3Label, href: _related3Href },
    { label: _related4Label, href: _related4Href },
    { label: _related5Label, href: _related5Href },
  ].filter((r) => r.label && r.href)

  // JSON-LD: DefinedTerm schema built from Props
  const jsonLd = JSON.stringify({
    "@context": "https://schema.org",
    "@type": "DefinedTerm",
    "name": _term,
    "description": _definitionBody,
    "inDefinedTermSet": "https://llmcapsule.ai/glossary",
  })

  return (
    <>
      <style>{`
        @import url('https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700;800&family=JetBrains+Mono:wght@400;500;600&display=swap');

        /* ── Root ─────────────────────────────────────────── */
        .gd-root {
          width: 100%;
          container-type: inline-size;
          font-family: var(--f-display, 'Inter', -apple-system, BlinkMacSystemFont, system-ui, sans-serif);
          color: var(--c-ink, #0f1130);
          background-color: var(--c-bg, #ffffff);
          -webkit-font-smoothing: antialiased;
          word-break: keep-all;
          overflow-wrap: break-word;
        }

        /* ── Container ────────────────────────────────────── */
        .gd-container {
          max-width: var(--container-max, 1280px);
          margin: 0 auto;
          padding: 0 var(--s-page, clamp(20px, 4vw, 80px));
        }

        /* ── 1. Article Hero ──────────────────────────────── */
        .gd-hero {
          padding: clamp(60px, 8vw, 100px) 0 clamp(40px, 5vw, 64px);
          border-bottom: 1px solid var(--c-rule, #e5e7eb);
        }

        .gd-hero__inner {
          max-width: 860px;
          margin: 0 auto;
        }

        .gd-hero__back {
          display: inline-flex;
          align-items: center;
          gap: 6px;
          font-size: 13px;
          font-weight: 600;
          color: var(--c-primary, #5b4fe9);
          text-decoration: none;
          letter-spacing: 0.01em;
          margin-bottom: 28px;
          transition: color 0.15s;
        }
        .gd-hero__back:hover { color: var(--c-primary-dark, #3b2fbf); }

        .gd-hero__title {
          font-size: clamp(32px, 4.5vw, 56px);
          font-weight: 700;
          line-height: 1.12;
          letter-spacing: -0.02em;
          color: var(--c-ink, #0f1130);
          margin: 0 0 20px;
          max-width: 860px;
        }

        .gd-hero__lead {
          font-size: clamp(16px, 1.4vw, 19px);
          line-height: 1.65;
          color: var(--c-ink-soft, #3a3d5e);
          margin: 0 0 28px;
          max-width: 760px;
        }

        .gd-hero__meta {
          display: flex;
          flex-wrap: wrap;
          align-items: center;
          gap: 10px 16px;
        }

        .gd-meta__chip {
          display: inline-flex;
          align-items: center;
          padding: 4px 12px;
          border-radius: 999px;
          background-color: var(--c-primary-soft, #eeebfe);
          color: var(--c-primary, #5b4fe9);
          font-size: 12px;
          font-weight: 700;
          letter-spacing: 0.06em;
          text-transform: uppercase;
        }

        /* ── 2. Definition block ──────────────────────────── */
        .gd-def-wrap {
          padding: clamp(40px, 5vw, 72px) 0;
          border-bottom: 1px solid var(--c-rule, #e5e7eb);
        }

        .gd-def {
          max-width: 880px;
          margin: 0 auto;
          background-color: var(--c-bg-dark, #0f1130);
          border-radius: var(--r-lg, 16px);
          padding: 32px 36px;
        }

        .gd-def__label {
          font-family: var(--f-mono, 'JetBrains Mono', 'SF Mono', Consolas, monospace);
          font-size: 11px;
          font-weight: 600;
          letter-spacing: 0.12em;
          text-transform: uppercase;
          color: var(--c-primary, #5b4fe9);
          margin-bottom: 14px;
        }

        .gd-def__body {
          font-size: 16px;
          line-height: 1.7;
          color: rgba(255, 255, 255, 0.88);
          margin: 0;
        }

        .gd-def__body strong {
          color: #ffffff;
          font-weight: 700;
        }

        /* ── 3. Article Body ──────────────────────────────── */
        .gd-body-wrap {
          padding: clamp(48px, 6vw, 96px) 0;
          border-bottom: 1px solid var(--c-rule, #e5e7eb);
        }

        .gd-body {
          max-width: 760px;
          margin: 0 auto;
        }

        /* Headings inside body */
        .gd-body h2 {
          font-size: clamp(22px, 2.2vw, 28px);
          font-weight: 700;
          line-height: 1.2;
          letter-spacing: -0.02em;
          color: var(--c-ink, #0f1130);
          margin: 0 0 18px;
          padding-top: 40px;
          border-top: 2px solid var(--c-rule, #e5e7eb);
        }

        .gd-body h2:first-child {
          padding-top: 0;
          border-top: none;
        }

        .gd-body h3 {
          font-size: clamp(17px, 1.5vw, 20px);
          font-weight: 700;
          line-height: 1.25;
          letter-spacing: -0.01em;
          color: var(--c-ink, #0f1130);
          margin: 32px 0 10px;
        }

        /* Paragraphs */
        .gd-body p {
          font-size: 17px;
          line-height: 1.75;
          color: var(--c-ink-soft, #3a3d5e);
          margin: 0 0 18px;
        }

        .gd-body p:last-child { margin-bottom: 0; }

        .gd-body p strong {
          color: var(--c-ink, #0f1130);
          font-weight: 700;
        }

        /* Lists */
        .gd-body ul,
        .gd-body ol {
          margin: 0 0 24px 0;
          padding-left: 24px;
        }

        .gd-body li {
          font-size: 17px;
          line-height: 1.7;
          color: var(--c-ink-soft, #3a3d5e);
          margin-bottom: 10px;
        }

        .gd-body li strong {
          color: var(--c-ink, #0f1130);
          font-weight: 700;
        }

        .gd-body li:last-child { margin-bottom: 0; }

        /* Blockquote */
        .gd-body blockquote {
          margin: 28px 0;
          padding: 20px 24px;
          border-left: 3px solid var(--c-primary, #5b4fe9);
          background-color: var(--c-primary-soft, #eeebfe);
          border-radius: 0 var(--r-sm, 6px) var(--r-sm, 6px) 0;
        }

        .gd-body blockquote p {
          margin: 0;
          color: var(--c-ink, #0f1130);
          font-style: italic;
        }

        /* Inline code */
        .gd-body code {
          font-family: var(--f-mono, 'JetBrains Mono', 'SF Mono', Consolas, monospace);
          font-size: 14px;
          background-color: var(--c-bg-soft, #f7f8fb);
          border: 1px solid var(--c-rule, #e5e7eb);
          border-radius: var(--r-sm, 6px);
          padding: 2px 7px;
          color: var(--c-ink, #0f1130);
        }

        /* Code block (pre) */
        .gd-body pre {
          background-color: var(--c-bg-dark, #0f1130);
          border-radius: var(--r-md, 10px);
          padding: 24px;
          margin: 24px 0;
          overflow-x: auto;
          scrollbar-width: none;
        }
        .gd-body pre::-webkit-scrollbar { display: none; }

        .gd-body pre code {
          font-family: var(--f-mono, 'JetBrains Mono', 'SF Mono', Consolas, monospace);
          font-size: 14px;
          background: none;
          border: none;
          padding: 0;
          color: rgba(255, 255, 255, 0.9);
          line-height: 1.65;
        }

        /* Table */
        .gd-body table {
          width: 100%;
          border-collapse: collapse;
          margin: 28px 0;
          font-size: 15px;
        }

        .gd-body th,
        .gd-body td {
          padding: 12px 16px;
          text-align: left;
          border-bottom: 1px solid var(--c-rule, #e5e7eb);
          line-height: 1.5;
          color: var(--c-ink-soft, #3a3d5e);
        }

        .gd-body th {
          font-weight: 700;
          color: var(--c-ink, #0f1130);
          background-color: var(--c-bg-soft, #f7f8fb);
        }

        .gd-body tr:last-child td { border-bottom: none; }

        /* Callout box (for <div class="callout"> inside _bodyHtml) */
        .gd-body .callout {
          padding: 20px 24px;
          background-color: var(--c-primary-soft, #eeebfe);
          border-left: 3px solid var(--c-primary, #5b4fe9);
          border-radius: 0 var(--r-sm, 6px) var(--r-sm, 6px) 0;
          margin: 28px 0;
          font-size: 15px;
          line-height: 1.65;
          color: var(--c-ink, #0f1130);
        }

        .gd-body .callout strong {
          color: var(--c-ink, #0f1130);
          font-weight: 700;
        }

        /* Takeaways box */
        .gd-body .takeaways {
          background-color: var(--c-bg-soft, #f7f8fb);
          border: 1px solid var(--c-rule, #e5e7eb);
          border-radius: var(--r-md, 10px);
          padding: 24px 28px;
          margin: 28px 0;
        }

        .gd-body .takeaways__label {
          font-family: var(--f-mono, 'JetBrains Mono', 'SF Mono', Consolas, monospace);
          font-size: 11px;
          font-weight: 600;
          letter-spacing: 0.1em;
          text-transform: uppercase;
          color: var(--c-muted, #6b7280);
          margin-bottom: 12px;
        }

        .gd-body .takeaways ul {
          margin: 0;
          padding-left: 20px;
        }

        .gd-body .takeaways li {
          font-size: 15px;
        }

        /* Inline links inside body */
        .gd-body a {
          color: var(--c-primary, #5b4fe9);
          text-decoration: none;
          border-bottom: 1px solid transparent;
          transition: border-color 0.15s, color 0.15s;
        }
        .gd-body a:hover {
          color: var(--c-primary-dark, #3b2fbf);
          border-bottom-color: var(--c-primary-dark, #3b2fbf);
        }

        /* ── 4. Related Terms ─────────────────────────────── */
        .gd-related {
          padding: clamp(48px, 6vw, 80px) 0;
          background-color: var(--c-bg-soft, #f7f8fb);
        }

        .gd-related__label {
          font-family: var(--f-mono, 'JetBrains Mono', 'SF Mono', Consolas, monospace);
          font-size: 11px;
          font-weight: 600;
          letter-spacing: 0.12em;
          text-transform: uppercase;
          color: var(--c-muted, #6b7280);
          margin-bottom: 20px;
        }

        .gd-related__list {
          list-style: none;
          margin: 0;
          padding: 0;
          display: flex;
          flex-direction: column;
          gap: 0;
        }

        .gd-related__item {
          border-top: 1px solid var(--c-rule, #e5e7eb);
        }

        .gd-related__item:last-child {
          border-bottom: 1px solid var(--c-rule, #e5e7eb);
        }

        .gd-related__link {
          display: flex;
          align-items: center;
          justify-content: space-between;
          gap: 16px;
          padding: 16px 4px;
          font-size: 15px;
          font-weight: 500;
          color: var(--c-ink, #0f1130);
          text-decoration: none;
          transition: color 0.15s;
        }

        .gd-related__link:hover {
          color: var(--c-primary, #5b4fe9);
        }

        .gd-related__link-arrow {
          font-size: 16px;
          color: var(--c-primary, #5b4fe9);
          flex-shrink: 0;
          transition: transform 0.15s;
        }

        .gd-related__link:hover .gd-related__link-arrow {
          transform: translateX(3px);
        }

        /* ── Container query: mobile adjustments ─────────── */
        @container (max-width: 767px) {
          .gd-hero { padding-top: 48px; }
          .gd-hero__title { font-size: 28px; }
          .gd-hero__lead { font-size: 16px; }
          .gd-def { padding: 24px 20px; border-radius: var(--r-md, 10px); }
          .gd-body p,
          .gd-body li { font-size: 16px; }
          .gd-body h2 { padding-top: 28px; }
        }
      `}</style>

      {/* JSON-LD: DefinedTerm schema */}
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: jsonLd }}
      />

      <div className="gd-root">

        {/* ── 1. Hero ── */}
        <section className="gd-hero">
          <div className="gd-container">
            <div className="gd-hero__inner">
              <a href={_backHref} className="gd-hero__back">{_backLabel}</a>
              <h1 className="gd-hero__title">{_term}</h1>
              <p className="gd-hero__lead">{_lead}</p>
              <div className="gd-hero__meta">
                <span className="gd-meta__chip">{_category}</span>
              </div>
            </div>
          </div>
        </section>

        {/* ── 2. Definition block ── */}
        <div className="gd-def-wrap">
          <div className="gd-container">
            <div className="gd-def">
              <div className="gd-def__label">{_definitionLabel}</div>
              <p className="gd-def__body">{_definitionBody}</p>
            </div>
          </div>
        </div>

        {/* ── 3. Article Body ── */}
        <div className="gd-body-wrap">
          <div className="gd-container">
            <article
              className="gd-body"
              dangerouslySetInnerHTML={{ __html: _bodyHtml }}
            />
          </div>
        </div>

        {/* ── 4. Related Terms ── */}
        {relatedItems.length > 0 && (
          <div className="gd-related">
            <div className="gd-container">
              <div className="gd-related__label">Related terms</div>
              <ul className="gd-related__list">
                {relatedItems.map((item, i) => (
                  <li key={i} className="gd-related__item">
                    <a href={item.href} className="gd-related__link">
                      <span>{item.label}</span>
                      <span className="gd-related__link-arrow" aria-hidden="true">→</span>
                    </a>
                  </li>
                ))}
              </ul>
            </div>
          </div>
        )}

      </div>
    </>
  )
}

addPropertyControls(OperationalData, {
  locale: { type: ControlType.Enum, title: "Locale", options: ["en", "ko", "de"], optionTitles: ["English", "한국어", "Deutsch"], defaultValue: "en" },
  backLabel: { type: ControlType.String, title: "Back Label", defaultValue: "" },
  backHref: { type: ControlType.String, title: "Back URL", defaultValue: "" },
  term: { type: ControlType.String, title: "Term", defaultValue: "" },
  lead: { type: ControlType.String, title: "Lead", defaultValue: "", displayTextArea: true },
  category: { type: ControlType.String, title: "Category", defaultValue: "" },
  definitionLabel: { type: ControlType.String, title: "Definition Label", defaultValue: "" },
  definitionBody: { type: ControlType.String, title: "Definition Body", defaultValue: "", displayTextArea: true },
  bodyHtml: { type: ControlType.String, title: "Body HTML", defaultValue: "", displayTextArea: true },
  related1Label: { type: ControlType.String, title: "Related 1 Label", defaultValue: "" },
  related1Href: { type: ControlType.String, title: "Related 1 URL", defaultValue: "" },
  related2Label: { type: ControlType.String, title: "Related 2 Label", defaultValue: "" },
  related2Href: { type: ControlType.String, title: "Related 2 URL", defaultValue: "" },
  related3Label: { type: ControlType.String, title: "Related 3 Label", defaultValue: "" },
  related3Href: { type: ControlType.String, title: "Related 3 URL", defaultValue: "" },
  related4Label: { type: ControlType.String, title: "Related 4 Label", defaultValue: "" },
  related4Href: { type: ControlType.String, title: "Related 4 URL", defaultValue: "" },
  related5Label: { type: ControlType.String, title: "Related 5 Label", defaultValue: "" },
  related5Href: { type: ControlType.String, title: "Related 5 URL", defaultValue: "" },
})
