import { addPropertyControls, ControlType } from "framer"

// GlossaryPage_OperationalData
// Content component for /glossary/operational-data
// Uses GlossaryDetail layout: Hero → Definition → Article Body → Related Terms
// v6.2 rules: var(--c-*) tokens, @container queries, Inter font, no gradient buttons, no !important
// Props match GlossaryDetail CMS Collection schema

interface Props {
  // Hero
  backLabel?: string
  backHref?: string
  term?: string
  lead?: string
  category?: string

  // Definition block
  definitionLabel?: string
  definitionBody?: string

  // Body — rich HTML string rendered with dangerouslySetInnerHTML
  bodyHtml?: string

  // Related terms — simple link list (up to 5)
  related1Label?: string
  related1Href?: string
  related2Label?: string
  related2Href?: string
  related3Label?: string
  related3Href?: string
  related4Label?: string
  related4Href?: string
  related5Label?: string
  related5Href?: string
}

const DEFAULT_BODY_HTML = `
<h2>What it is not</h2>
<p>Operational data is not the same as PII. PII is identifiable individual fields — names, contact info, financial identifiers. Operational data may contain PII as a subset, but its sensitivity comes primarily from structure, sequence, and aggregate pattern.</p>

<h2>Examples by industry</h2>

<h3>Telecom</h3>
<ul>
<li>Network topology, device IDs, site IDs, circuit IDs, IP ranges</li>
<li>Alarm sequences, traffic anomaly patterns</li>
<li>Incident records with customer-impact and SLA risk</li>
<li>NOC response history, runbooks, change management records</li>
</ul>

<h3>OT / Industrial</h3>
<ul>
<li>Asset IDs, PLC/ICS alerts, vulnerability records</li>
<li>Plant operation context, patch constraints</li>
<li>Vendor and device references</li>
</ul>

<h3>Healthcare</h3>
<ul>
<li>Clinical workflow, lab result flow, prescription flow</li>
<li>Hospital operation records, claim review context</li>
</ul>

<h3>Defense / Public sector</h3>
<ul>
<li>Mission logs, operation briefs</li>
<li>Access-controlled context, command workflow</li>
</ul>

<h3>Finance / Insurance</h3>
<ul>
<li>Risk review, transaction anomaly</li>
<li>Audit trail, approval workflow, internal control evidence</li>
</ul>

<h2>Why it needs a context-preserving data layer for AI</h2>
<p>Operational data leaks information through structure (the topology itself reveals the network), sequence (the alarm pattern reveals the fault chain), and aggregate (the incident frequency reveals the customer segment). PII filtering does not bound this leakage. The <a href="/resources/glossary/ai-ready-operational-layer">context-preserving data layer for AI</a> applies <a href="/resources/glossary/structure-preserving-encapsulation">structure-preserving encapsulation</a> with <a href="/resources/glossary/differential-privacy">differential-privacy-based protection</a> to bring operational data safely into LLM workflows.</p>

<h2>Reference statement</h2>
<blockquote>Operational data is the data your business runs on. AI cannot reach it through a PII guardrail. The context-preserving data layer for AI was built for this category specifically.</blockquote>
`

export default function GlossaryPage_OperationalData({
  backLabel = "← Glossary",
  backHref = "/glossary",
  term = "Operational Data",
  lead = "The data your business actually runs on. Not the same as PII. Not protected the same way.",
  category = "GLOSSARY",
  definitionLabel = "Definition",
  definitionBody = "Operational data is the structured and unstructured enterprise data generated by ongoing business operations. It includes the records, logs, configurations, alarms, tickets, runbooks, workflows, and contextual references that operations teams produce and consume daily.",
  bodyHtml = DEFAULT_BODY_HTML,
  related1Label = "context-preserving data layer for AI",
  related1Href = "/glossary/ai-ready-operational-layer",
  related2Label = "Structure-preserving encapsulation",
  related2Href = "/glossary/structure-preserving-encapsulation",
  related3Label = "Differential privacy",
  related3Href = "/glossary/differential-privacy",
  related4Label = "",
  related4Href = "",
  related5Label = "",
  related5Href = "",
}: Props) {
  const relatedItems = [
    { label: related1Label, href: related1Href },
    { label: related2Label, href: related2Href },
    { label: related3Label, href: related3Href },
    { label: related4Label, href: related4Href },
    { label: related5Label, href: related5Href },
  ].filter((r) => r.label && r.href)

  // JSON-LD: DefinedTerm schema
  const jsonLd = JSON.stringify({
    "@context": "https://schema.org",
    "@type": "DefinedTerm",
    "name": term,
    "description": definitionBody,
    "inDefinedTermSet": "https://llmcapsule.ai/glossary",
    "url": "https://llmcapsule.ai/resources/glossary/operational-data",
  })

  return (
    <>
      <style>{`
        @import url('https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700;800&family=JetBrains+Mono:wght@400;500;600&display=swap');

        /* ── Root ─────────────────────────────────────────── */
        .god-root {
          width: 100%;
          container-type: inline-size;
          font-family: var(--f-display, 'Inter', -apple-system, BlinkMacSystemFont, system-ui, sans-serif);
          color: var(--c-ink, #0f1130);
          background-color: var(--c-bg, #ffffff);
          -webkit-font-smoothing: antialiased;
          word-break: keep-all;
          overflow-wrap: break-word;
        }

        /* ── Container ────────────────────────────────────── */
        .god-container {
          max-width: var(--container-max, 1280px);
          margin: 0 auto;
          padding: 0 var(--s-page, clamp(20px, 4vw, 80px));
        }

        /* ── 1. Hero ──────────────────────────────────────── */
        .god-hero {
          padding: clamp(60px, 8vw, 100px) 0 clamp(40px, 5vw, 64px);
          border-bottom: 1px solid var(--c-rule, #e5e7eb);
        }

        .god-hero__back {
          display: inline-flex;
          align-items: center;
          gap: 6px;
          font-size: 13px;
          font-weight: 600;
          color: var(--c-primary, #5b4fe9);
          text-decoration: none;
          letter-spacing: 0.01em;
          margin-bottom: 28px;
          transition: color 0.15s;
        }
        .god-hero__back:hover { color: var(--c-primary-dark, #3b2fbf); }

        .god-hero__title {
          font-size: clamp(32px, 4.5vw, 56px);
          font-weight: 700;
          line-height: 1.12;
          letter-spacing: -0.02em;
          color: var(--c-ink, #0f1130);
          margin: 0 0 20px;
          max-width: 860px;
        }

        .god-hero__lead {
          font-size: clamp(16px, 1.4vw, 19px);
          line-height: 1.65;
          color: var(--c-ink-soft, #3a3d5e);
          margin: 0 0 28px;
          max-width: 760px;
        }

        .god-hero__meta {
          display: flex;
          flex-wrap: wrap;
          align-items: center;
          gap: 10px 16px;
        }

        .god-meta__chip {
          display: inline-flex;
          align-items: center;
          padding: 4px 12px;
          border-radius: 999px;
          background-color: var(--c-primary-soft, #eeebfe);
          color: var(--c-primary, #5b4fe9);
          font-size: 12px;
          font-weight: 700;
          letter-spacing: 0.06em;
          text-transform: uppercase;
        }

        /* ── 2. Definition block ──────────────────────────── */
        .god-def-wrap {
          padding: clamp(40px, 5vw, 72px) 0;
          border-bottom: 1px solid var(--c-rule, #e5e7eb);
        }

        .god-def {
          max-width: 880px;
          background-color: var(--c-bg-dark, #0f1130);
          border-radius: var(--r-lg, 16px);
          padding: 32px 36px;
        }

        .god-def__label {
          font-family: var(--f-mono, 'JetBrains Mono', 'SF Mono', Consolas, monospace);
          font-size: 11px;
          font-weight: 600;
          letter-spacing: 0.12em;
          text-transform: uppercase;
          color: var(--c-primary, #5b4fe9);
          margin-bottom: 14px;
        }

        .god-def__body {
          font-size: 16px;
          line-height: 1.7;
          color: rgba(255, 255, 255, 0.88);
          margin: 0;
        }

        .god-def__body strong {
          color: #ffffff;
          font-weight: 700;
        }

        /* ── 3. Article Body ──────────────────────────────── */
        .god-body-wrap {
          padding: clamp(48px, 6vw, 96px) 0;
          border-bottom: 1px solid var(--c-rule, #e5e7eb);
        }

        .god-body {
          max-width: 760px;
        }

        .god-body h2 {
          font-size: clamp(22px, 2.2vw, 28px);
          font-weight: 700;
          line-height: 1.2;
          letter-spacing: -0.02em;
          color: var(--c-ink, #0f1130);
          margin: 0 0 18px;
          padding-top: 40px;
          border-top: 2px solid var(--c-rule, #e5e7eb);
        }

        .god-body h2:first-child {
          padding-top: 0;
          border-top: none;
        }

        .god-body h3 {
          font-size: clamp(17px, 1.5vw, 20px);
          font-weight: 700;
          line-height: 1.25;
          letter-spacing: -0.01em;
          color: var(--c-ink, #0f1130);
          margin: 32px 0 10px;
        }

        .god-body p {
          font-size: 17px;
          line-height: 1.75;
          color: var(--c-ink-soft, #3a3d5e);
          margin: 0 0 18px;
        }

        .god-body p:last-child { margin-bottom: 0; }

        .god-body p strong {
          color: var(--c-ink, #0f1130);
          font-weight: 700;
        }

        .god-body ul,
        .god-body ol {
          margin: 0 0 24px 0;
          padding-left: 24px;
        }

        .god-body li {
          font-size: 17px;
          line-height: 1.7;
          color: var(--c-ink-soft, #3a3d5e);
          margin-bottom: 10px;
        }

        .god-body li strong {
          color: var(--c-ink, #0f1130);
          font-weight: 700;
        }

        .god-body li:last-child { margin-bottom: 0; }

        .god-body blockquote {
          margin: 28px 0;
          padding: 20px 24px;
          border-left: 3px solid var(--c-primary, #5b4fe9);
          background-color: var(--c-primary-soft, #eeebfe);
          border-radius: 0 var(--r-sm, 6px) var(--r-sm, 6px) 0;
        }

        .god-body blockquote p {
          margin: 0;
          color: var(--c-ink, #0f1130);
          font-style: italic;
        }

        .god-body code {
          font-family: var(--f-mono, 'JetBrains Mono', 'SF Mono', Consolas, monospace);
          font-size: 14px;
          background-color: var(--c-bg-soft, #f7f8fb);
          border: 1px solid var(--c-rule, #e5e7eb);
          border-radius: var(--r-sm, 6px);
          padding: 2px 7px;
          color: var(--c-ink, #0f1130);
        }

        .god-body pre {
          background-color: var(--c-bg-dark, #0f1130);
          border-radius: var(--r-md, 10px);
          padding: 24px;
          margin: 24px 0;
          overflow-x: auto;
          scrollbar-width: none;
        }
        .god-body pre::-webkit-scrollbar { display: none; }

        .god-body pre code {
          font-family: var(--f-mono, 'JetBrains Mono', 'SF Mono', Consolas, monospace);
          font-size: 14px;
          background: none;
          border: none;
          padding: 0;
          color: rgba(255, 255, 255, 0.9);
          line-height: 1.65;
        }

        .god-body a {
          color: var(--c-primary, #5b4fe9);
          text-decoration: none;
          border-bottom: 1px solid transparent;
          transition: border-color 0.15s, color 0.15s;
        }
        .god-body a:hover {
          color: var(--c-primary-dark, #3b2fbf);
          border-bottom-color: var(--c-primary-dark, #3b2fbf);
        }

        /* ── 4. Related Terms ─────────────────────────────── */
        .god-related {
          padding: clamp(48px, 6vw, 80px) 0;
          background-color: var(--c-bg-soft, #f7f8fb);
        }

        .god-related__label {
          font-family: var(--f-mono, 'JetBrains Mono', 'SF Mono', Consolas, monospace);
          font-size: 11px;
          font-weight: 600;
          letter-spacing: 0.12em;
          text-transform: uppercase;
          color: var(--c-muted, #6b7280);
          margin-bottom: 20px;
        }

        .god-related__list {
          list-style: none;
          margin: 0;
          padding: 0;
          display: flex;
          flex-direction: column;
          gap: 0;
        }

        .god-related__item {
          border-top: 1px solid var(--c-rule, #e5e7eb);
        }

        .god-related__item:last-child {
          border-bottom: 1px solid var(--c-rule, #e5e7eb);
        }

        .god-related__link {
          display: flex;
          align-items: center;
          justify-content: space-between;
          gap: 16px;
          padding: 16px 4px;
          font-size: 15px;
          font-weight: 500;
          color: var(--c-ink, #0f1130);
          text-decoration: none;
          transition: color 0.15s;
        }

        .god-related__link:hover {
          color: var(--c-primary, #5b4fe9);
        }

        .god-related__link-arrow {
          font-size: 16px;
          color: var(--c-primary, #5b4fe9);
          flex-shrink: 0;
          transition: transform 0.15s;
        }

        .god-related__link:hover .god-related__link-arrow {
          transform: translateX(3px);
        }

        /* ── Container queries ────────────────────────────── */
        @container (max-width: 767px) {
          .god-hero { padding-top: 48px; }
          .god-hero__title { font-size: 28px; }
          .god-hero__lead { font-size: 16px; }
          .god-def { padding: 24px 20px; border-radius: var(--r-md, 10px); }
          .god-body p,
          .god-body li { font-size: 16px; }
          .god-body h2 { padding-top: 28px; }
        }
      `}</style>

      {/* JSON-LD: DefinedTerm schema */}
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: jsonLd }}
      />

      <div className="god-root">

        {/* ── 1. Hero ── */}
        <section className="god-hero">
          <div className="god-container">
            <a href={backHref} className="god-hero__back">{backLabel}</a>
            <h1 className="god-hero__title">{term}</h1>
            <p className="god-hero__lead">{lead}</p>
            <div className="god-hero__meta">
              <span className="god-meta__chip">{category}</span>
            </div>
          </div>
        </section>

        {/* ── 2. Definition block ── */}
        <div className="god-def-wrap">
          <div className="god-container">
            <div className="god-def">
              <div className="god-def__label">{definitionLabel}</div>
              <p className="god-def__body">{definitionBody}</p>
            </div>
          </div>
        </div>

        {/* ── 3. Article Body ── */}
        <div className="god-body-wrap">
          <div className="god-container">
            <article
              className="god-body"
              dangerouslySetInnerHTML={{ __html: bodyHtml }}
            />
          </div>
        </div>

        {/* ── 4. Related Terms ── */}
        {relatedItems.length > 0 && (
          <div className="god-related">
            <div className="god-container">
              <div className="god-related__label">Related terms</div>
              <ul className="god-related__list">
                {relatedItems.map((item, i) => (
                  <li key={i} className="god-related__item">
                    <a href={item.href} className="god-related__link">
                      <span>{item.label}</span>
                      <span className="god-related__link-arrow" aria-hidden="true">→</span>
                    </a>
                  </li>
                ))}
              </ul>
            </div>
          </div>
        )}

      </div>
    </>
  )
}

addPropertyControls(GlossaryPage_OperationalData, {
  // Hero
  backLabel: { type: ControlType.String, title: "Back Label",   defaultValue: "← Glossary" },
  backHref:  { type: ControlType.String, title: "Back URL",     defaultValue: "/glossary" },
  term:      { type: ControlType.String, title: "Term",         defaultValue: "Operational Data" },
  lead:      { type: ControlType.String, title: "Lead",         defaultValue: "The data your business actually runs on. Not the same as PII. Not protected the same way.", displayTextArea: true },
  category:  { type: ControlType.String, title: "Category",     defaultValue: "GLOSSARY" },

  // Definition block
  definitionLabel: { type: ControlType.String, title: "Definition Label", defaultValue: "Definition" },
  definitionBody:  {
    type: ControlType.String,
    title: "Definition Body",
    defaultValue: "Operational data is the structured and unstructured enterprise data generated by ongoing business operations. It includes the records, logs, configurations, alarms, tickets, runbooks, workflows, and contextual references that operations teams produce and consume daily.",
    displayTextArea: true,
  },

  // Body HTML
  bodyHtml: { type: ControlType.String, title: "Body HTML", defaultValue: DEFAULT_BODY_HTML, displayTextArea: true },

  // Related terms
  related1Label: { type: ControlType.String, title: "Related 1 Label", defaultValue: "context-preserving data layer for AI" },
  related1Href:  { type: ControlType.String, title: "Related 1 URL",   defaultValue: "/glossary/ai-ready-operational-layer" },
  related2Label: { type: ControlType.String, title: "Related 2 Label", defaultValue: "Structure-preserving encapsulation" },
  related2Href:  { type: ControlType.String, title: "Related 2 URL",   defaultValue: "/glossary/structure-preserving-encapsulation" },
  related3Label: { type: ControlType.String, title: "Related 3 Label", defaultValue: "Differential privacy" },
  related3Href:  { type: ControlType.String, title: "Related 3 URL",   defaultValue: "/glossary/differential-privacy" },
  related4Label: { type: ControlType.String, title: "Related 4 Label", defaultValue: "" },
  related4Href:  { type: ControlType.String, title: "Related 4 URL",   defaultValue: "" },
  related5Label: { type: ControlType.String, title: "Related 5 Label", defaultValue: "" },
  related5Href:  { type: ControlType.String, title: "Related 5 URL",   defaultValue: "" },
})
